apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-roll-test
spec:
  strategy:
    blueGreen:
      activeService: argo-roll-test
      previewService: argo-roll-test-preview
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        version: old
    spec:
      containers:
        - name: argo-roll-test
          image: ayoobki/argo-roll-test:old
          ports:
            - containerPort: 6000
