apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-roll-test
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: argo-roll-test
      previewService: argo-roll-test-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: argo-roll-test
  template:
    metadata:
      labels:
        app: argo-roll-test
        version: new 
    spec:
      containers:
        - name: argo-roll-test
          image: ayoobki/argo-roll-test:new  
          ports:
            - containerPort: 6000
